### ISSUE TITLE
Error while Updating

### ISSUE THREAD

**Issue by JamieH** [tgstation/tgstation-server-tools#18] opened 2017-06-05 02:37 UTC
<img width="908" alt="screen shot 2017-06-05 at 03 37 48" src="https://cloud.githubusercontent.com/assets/1857320/26768512/49e5b9bc-49a0-11e7-8eed-49591872af8f.png">

**Comment by Cyberboss** [comment] 2017-06-05 15:15
Can I ask for repro steps?

**Comment by Cyberboss** [comment] 2017-06-05 15:43
I've seen this one myself before, but I've never been able to track it down. The directory isn't supposed to be empty because it's a symlink. Therefore windows shouldn't care. But it throws this every so often and I can't figure out why.

**Comment by JamieH** [comment] 2017-06-06 13:00
I have no repro steps, sorry.

**Comment by Cyberboss** [comment] 2017-06-12 19:02
What happened was it tried to recursively delete either the data or config dir. So this is a dupe of #42.

**Closed by Cyberboss** 2017-06-12 19:02 UTC
Labels: Bug
